### ISSUE TITLE
Version 2.4.0 introduced mandatory dependency on circe

### ISSUE THREAD

**Issue by augi** [avast/scala-hashes#23]
Unfortunately, after updating to `2.4.0`, our `sbt` builds are failing with this:
```
Symbol 'type io.circe.Encoder' is missing from the classpath.
[error] This symbol is required by 'lazy value com.avast.scala.hashes.Sha256.Sha256Encoder'.
[error] Make sure that type Encoder is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Sha256.class' was compiled against an incompatible version of io.circe.
```
Do you have any idea how to overcome this, please? @sideeffffect @jakubjanecek 

Gradle projects work well.

**Comment by jakubjanecek** [comment]
I think this is binary incompatibility hidden in Gradle but manifesting itself in sbt. I think it can be because of improvements in recent versions of Scala and sbt but I am just guessing.
Anyway, what is the version of `circe` you expect in your project? This library is using `0.13.0`.

**Comment by augi** [comment]
The problem is that the project doesn't use `circe` at all, so this is not a binary incompatibility thing. 

We have this problem is all the projects managed by `sbt` that **don't** use `circe`.

Gradle projects work fine, both compilation and runtime.

It actually looks like a bug in sbt that requires a dependency that is not actually required. If there is not any workaround in sbt, then I'm afraid we will have to revert changes from #21

**Comment by jakubjanecek** [comment]
OK, I was not aware of that change so it kind of makes sense. To me that change is a nasty trick that should have never been merged. The fact that it "works" is not a good reason to have library that depends on some other library without the dependency being declared - that is a direct line to trouble.

I guess sbt is more strict or is doing more with the bytecode and it's missing the `circe` dependency (because yes, thanks to how JVM works this should and works in runtime). How do you compile your project? Does this happen with regular compilation using `compile` or are you doing more and maybe run missinglink in your project? Because I think some linter could be the problem, not sbt or Scala compiler itself.

**Comment by augi** [comment]
Ah, sorry for mentioning you 😢 I thought you were for merging that PR, but it was @jendakol actually 👌 

I cannot verify it right now as `abt` doesn't work on Windows but I will try it later today.

But the error in CI seems to be reported by the following task, so I guess it is not caused by missinglink
```
(Compile / compileIncremental) Compilation failed
```

**Comment by jendakol** [comment]
Hey, I didn't say "merge it" nor I did formally hit the "approve" button 😄 (no hard feelings) I **only** helped explaining that the implicit magic around will work because it's lazy:
> Still, it's kind of... potentially dangerous. So I won't express my opinion on whether to use this or that, I just wanted to explain.

Plus, I'm still convinced we did this trick somewhere and it just worked - but it was in _Gradle times_ so now the situation may be (and obviously _is_ different).  
Anyway, I'm sorry about this doesn't work 😞

**Comment by jakubjanecek** [comment]
I found the exact issue.

The problem only appears when you compile with Scala 2.12 and the reason is that Scala collections in 2.12 (specifically method `map`) have implicit parameter of `CanBuildFrom` and this  implicit parameter causes the compiler to look for implicit values and triggers the search for this missing class. Scala 2.13 is fine because it no longer has this implicit parameter for the `map` method.

So yes, this trick works but not with implicits together. And I am quite sure Gradle would fail too, you probably use newer version of Scala in your Gradle projects.

All in all I still think this is a nasty trick that should not be used even when the usage is less ergonomic.

**Comment by augi** [comment]
Yeah, we have all our Gradle projects on 2.13 only (even libraries are not cross-compiled for Scala 2.12).

**Comment by augi** [comment]
Instead of reverting the #21, I propose to create a new _explicit_ module with circe support.
